default_install_hook_types: [pre-commit, post-checkout]

repos:

-   repo: https://github.com/pycqa/isort
    rev: '6.0.1'
    hooks:
        -   id: isort
            name: isort

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.13.0'
    hooks:
    -   id: ruff-check
        args: ["--fix", "--ignore=RUF002"]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]

-   repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-docstrings
            - flake8-broken-line
            - flake8-eradicate
            - flake8-functions
            - flake8-mutable
            - flake8-string-format
            - flake8-variables-names

-   repo: https://github.com/python-poetry/poetry
    rev: '2.2.0'
    hooks:
    -   id: poetry-check
        stages: [pre-commit]
    -   id: poetry-lock
        stages: [pre-commit]
    -   id: poetry-install
        stages: [post-checkout]
